<?php

/**
 * Plugin Name: TeckGlobal Image Convert WebP
 * Author: TeckGlobal LLC
 * Author URI: https://teck-global.com/
 * Plugin URI: https://teck-global.com/wordpress-plugins/
 * Description: WordPress image resize plugin to convert all uploaded images to WebP at 80 percent quality without breaking WordPress image sizes. If you enjoy this free product please donate at https://teck-global.com/buy-me-a-coffee/
 * Version: 1.0.0
 * License: GPL2
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: teckglobal-image-convert-webp
 * Requires at least: 5.0
 * Tested up to: 6.7
 * Requires PHP: 7.4 or later
 * WordPress Available: yes
 * Requires License: no
 */

if (!defined('ABSPATH')) {
    // Avoid direct calls to this file and prevent full path disclosure
    exit();
}

function convert_images_to_webp($file) {
    // Check if Imagick is available
    if (!class_exists('Imagick')) {
        return $file;
    }

    // Allowed image types
    $supported_types = ['image/jpeg', 'image/jpg', 'image/png'];

    // If the file is not a supported type, return it as-is
    if (!in_array($file['type'], $supported_types)) {
        return $file;
    }

    // Get the upload directory info
    $wp_upload_dir = wp_upload_dir();
    $original_file_path = $file['file'];
    $file_name = pathinfo($original_file_path, PATHINFO_FILENAME);
    $webp_file_path = trailingslashit($wp_upload_dir['path']) . $file_name . '.webp';

    // Check if the image is already WebP
    if (pathinfo($original_file_path, PATHINFO_EXTENSION) === 'webp') {
        return $file;
    }

    // Create WebP version using Imagick
    try {
        $image = new Imagick($original_file_path);
        $image->setImageFormat('webp');
        $image->setImageCompressionQuality(75); // Adjust quality as needed
        $image->stripImage(); // Remove metadata for smaller size
        $image->writeImage($webp_file_path);
        $image->clear();
        $image->destroy();
    } catch (Exception $e) {
        return $file; // If conversion fails, return original file
    }

    // Get all image sizes generated by WordPress
    $attachment_id = attachment_url_to_postid($file['url']);
    $metadata = wp_generate_attachment_metadata($attachment_id, $webp_file_path);
    wp_update_attachment_metadata($attachment_id, $metadata);

    // Return new WebP file info
    return [
        'file' => $webp_file_path,
        'url' => trailingslashit($wp_upload_dir['url']) . basename($webp_file_path),
        'type' => 'image/webp',
    ];
}

// Apply filter to all uploaded images
add_filter('wp_handle_upload', 'convert_images_to_webp');
